name: HOSTINGER
on:
  push:
    branches:
      - figma_updates # Ejecuta el script cada vez que haya un "push" a la rama main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Obtener el código del repositorio
        uses: actions/checkout@v4

      - name: ⚙️ Configurar el entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versión estable de Node.js

      - name: 📦 Instalar dependencias del proyecto
        run: npm install

      - name: 🏗️ Construir la versión de producción (Vite Build)
        run: npm run build
        
      - name: 🚀 Desplegar a Hostinger vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftp
          server: ftp.beardedmountaineerlodge.com
          port: 21
          username: u251936581.mycoandes
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
